### ISSUE TITLE
404 errors due to incorrect paths

### ISSUE THREAD

**Issue by strtw** [olostan/overproxy#1]
Great tool! I've tested it out on Mozilla and Google's home page using the index.html file as my test file and works as expected. However, when I've tried using the tool on a client site from within their network all the domain files are being served as if they were on my local. The only file I saved was their index.html so I'm seeing many 404 resource errors and the page isn't rendering properly. My goal is to be able to use lighthouse to do an audit with local overrides.

**Comment by olostan** [comment]
Can you elaborate little bit? Are you using 'localhost' or changing hosts file? Are 404s you get result of requests to localhost (or domain from hosts)? Are you using compression or not (`-c` option)

**Comment by strtw** [comment]
Glad to elaborate, this is the command I'm using:

`C:\Users\stuw\documents\workspace\overProxy\exampleSite\us\en> overproxy -t https://www.exampleSite.com/us/en/ -l .`

This is the overproxy message the command returns: 

`Overriding proxy for https://www.exampleSite.com/us/en/ from C:\Users\stuw\documents\workspace\overProxy\exampleSite\us\en
 is ready on http://localhost:8080`

I have one file saved to `C:\Users\stuw\documents\workspace\overProxy\exampleSite\us\en`, index.html

I believe the 404s are a result of requests being made to localhost, because the path to the resources look like: `<script type="text/javascript" src="/etc/clientlibs/granite/jquery.js"></script>` where the etc folder is within the localhost 8080 folder. Clicking into jquery.js, there is no file contents.

**Comment by olostan** [comment]
Actually it's what overproxy should do - if no file found locally, it should forward request to target site.

But when web site tries to open `/etc/clientlibs/...` it actually goes `/us/en/etc/clientlibs/...` and returns 404.

What I would advise to try is to run tool from `C:\Users\stuw\documents\workspace\overProxy\exampleSite` (without "es\en") and serve `https://www.exampleSite.com/`. But then navigate to `http://localhost:8080/en/us/`.

**Comment by strtw** [comment]
`C:\Users\stuw\documents\workspace\overProxy\exampleSite> overproxy -t https://www.exampleSite.com/ -l .
Overriding proxy for https://www.exampleSite.com/ from C:\Users\stuw\documents\workspace\overProxy\exampleSite is ready on
 http://localhost:8080` 

 index.html is located in `C:\Users\stuw\documents\workspace\overProxy\exampleSite`

I navigated to `localhost:8080` and all is working well now. Thanks!
